/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-07-25 10:48:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "_header.jsp", out, false);
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "_nav.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<header class=\"main\">\n");
      out.write("    <div class=\"header-content\">\n");
      out.write("        <div class=\"header-content-inner\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-md-6 col-md-offset-3\">\n");
      out.write("                    <div class=\"panel panel-default\">\n");
      out.write("                        <div class=\"panel-body\">\n");
      out.write("                            ");
if (session.getAttribute("error") != null){
      out.write("\n");
      out.write("                            <!-- Gerald TODO: Style error message -->\n");
      out.write("                            <h4 style=\"color: black;\">  ");
      out.print(session.getAttribute("error"));
      out.write("</h4>   \n");
      out.write("                            ");
  session.removeAttribute("error");
                                session.setAttribute("loginSource", "create_new_post");}
      out.write("\n");
      out.write("                            <!-- END -->\n");
      out.write("                            <h2 class=\"text-center primary\">Login</h2>\n");
      out.write("                            \n");
      out.write("                            <form action=\"/LoginServlet\" method=\"POST\" role=\"form\">\n");
      out.write("                                <div class=\"form-group form-group-lg col-md-12 text-left\"> \n");
      out.write("                                    <div class=\"input-group\"> \n");
      out.write("                                        <div class=\"input-group-addon\"><i class=\"fa fa-envelope fa-lg fa-fw\"></i></div> \n");
      out.write("                                        <input id=\"login-email\" class=\"form-control\" type=\"text\" placeholder=\"Your email address\" name=\"email\" required> \n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                                <div class=\"form-group form-group-lg col-md-12 text-left\"> \n");
      out.write("                                    <div class=\"input-group\"> \n");
      out.write("                                        <div class=\"input-group-addon\"><i class=\"fa fa-lock fa-lg fa-fw\"></i></div> \n");
      out.write("                                        <input id=\"login-password\" class=\"form-control\" type=\"password\" placeholder=\"password\" name=\"password\" required>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                                <div class=\"form-group form-group-lg col-md-12 text-left\"> \n");
      out.write("                                  <input type=\"submit\" class=\"btn btn-lg btn-block btn-primary btn-srad\" value=\"Login\"/>\n");
      out.write("                                </div>\n");
      out.write("                            </form>\n");
      out.write("                            <div class=\"form-group form-group-lg col-md-12 text-left\"> \n");
      out.write("                                <button class=\"btn btn-lg btn-block btn-info btn-srad\" target=\"_blank\">Login thru Facebook</button>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"form-group form-group-lg col-md-12 text-left\"> \n");
      out.write("                                <a href=\"/register.jsp\" class=\"btn btn-lg btn-block btn-default btn-srad\">New to Clockwork? Click Here</a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>                  \n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("  window.fbAsyncInit = function() {\n");
      out.write("    FB.init({\n");
      out.write("      appId      : '879787135436221',\n");
      out.write("      xfbml      : true,\n");
      out.write("      version    : 'v2.4'\n");
      out.write("    });\n");
      out.write("    \n");
      out.write("    FB.getLoginStatus(function(response) {\n");
      out.write("        statusChangeCallback(response);\n");
      out.write("    });\n");
      out.write("  };\n");
      out.write("\n");
      out.write("  (function(d, s, id){\n");
      out.write("     var js, fjs = d.getElementsByTagName(s)[0];\n");
      out.write("     if (d.getElementById(id)) {return;}\n");
      out.write("     js = d.createElement(s); js.id = id;\n");
      out.write("     js.src = \"//connect.facebook.net/en_US/sdk.js\";\n");
      out.write("     fjs.parentNode.insertBefore(js, fjs);\n");
      out.write("   }(document, 'script', 'facebook-jssdk'));\n");
      out.write("   \n");
      out.write("   function statusChangeCallback(response) {\n");
      out.write("    console.log('statusChangeCallback');\n");
      out.write("    console.log(response);\n");
      out.write("    // The response object is returned with a status field that lets the\n");
      out.write("    // app know the current login status of the person.\n");
      out.write("    // Full docs on the response object can be found in the documentation\n");
      out.write("    // for FB.getLoginStatus().\n");
      out.write("    if (response.status === 'connected') {\n");
      out.write("      // Logged into your app and Facebook.\n");
      out.write("      alert(\"logged in\");\n");
      out.write("    } else {\n");
      out.write("      FB.login(function(response){\n");
      out.write("  // Handle the response object, like in statusChangeCallback() in our demo\n");
      out.write("  // code.\n");
      out.write("});\n");
      out.write("    }\n");
      out.write("  }\n");
      out.write("</script>\n");
      out.write("                                \n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "_footer.jsp", out, false);
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
