/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
<<<<<<< HEAD
 * Generated at: 2015-07-23 09:28:11 UTC
=======
 * Generated at: 2015-07-22 12:30:15 UTC
>>>>>>> 9bd30ab842873ea5de372a0d5f99cced149ed30e
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "_header.jsp", out, false);
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "_nav.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<header class=\"main\">\n");
      out.write("  <div class=\"header-content\">\n");
      out.write("    <div class=\"header-content-inner\">\n");
      out.write("\n");
      out.write("\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-md-6 col-md-offset-3\">\n");
      out.write("          <div class=\"panel panel-default\">\n");
      out.write("            <div class=\"panel-body\">\n");
      out.write("              <h2 class=\"text-center primary\">Login</h2>\n");
      out.write("              <form action=\"/\" method=\"POST\" role=\"form\">\n");
      out.write("\n");
      out.write("                <div class=\"form-group form-group-lg col-md-12 text-left\"> \n");
      out.write("                  <div class=\"input-group\"> \n");
      out.write("                   <div class=\"input-group-addon\"><i class=\"fa fa-envelope fa-lg fa-fw\"></i></div> \n");
      out.write("                   <input id=\"login-email\" class=\"form-control\" type=\"text\" placeholder=\"Your email address\" name=\"email\" required> \n");
      out.write("                 </div>\n");
      out.write("               </div>\n");
      out.write("\n");
      out.write("               <div class=\"form-group form-group-lg col-md-12 text-left\"> \n");
      out.write("                <div class=\"input-group\"> \n");
      out.write("                 <div class=\"input-group-addon\"><i class=\"fa fa-lock fa-lg fa-fw\"></i></div> \n");
      out.write("                 <input id=\"login-password\" class=\"form-control\" type=\"password\" placeholder=\"password\" name=\"password\" required>\n");
      out.write("               </div>\n");
      out.write("             </div>\n");
      out.write("\n");
      out.write("             <div class=\"form-group form-group-lg col-md-12 text-left\"> \n");
      out.write("               <input type=\"submit\" class=\"btn btn-lg btn-block btn-primary btn-srad\" value=\"Login\"/>\n");
      out.write("             </div>\n");
      out.write("\n");
      out.write("           </form>\n");
      out.write("\n");
      out.write("           <div class=\"form-group form-group-lg col-md-12 text-left\"> \n");
      out.write("            <a href=\"/register.jsp\" class=\"btn btn-lg btn-block btn-default btn-srad\">New to Clockwork? Click Here</a>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("\n");
<<<<<<< HEAD
      out.write("<div>\n");
      out.write("    <div>\n");
      out.write("        <form action=\"/employer_login.jsp\" method=\"\"><input type=\"submit\" value=\"Employers click here\" /></form>\n");
      out.write("        <form action=\"/job_seeker_login.jsp\" method=\"\"><input type=\"submit\" value=\"Job Seekers click here\" /></form>\n");
=======
      out.write("        </div>\n");
      out.write("      </div>\n");
>>>>>>> 9bd30ab842873ea5de372a0d5f99cced149ed30e
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</header>\n");
      out.write("\n");
<<<<<<< HEAD
      out.write("<hr class=\"grey\">\n");
      out.write("<footer>\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-md-4\">\n");
      out.write("                <span class=\"copyright\">Copyright © Clockwork 2015</span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-4\">\n");
      out.write("                <ul class=\"list-inline social-buttons text-center\">\n");
      out.write("                    <li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\n");
      out.write("                    <li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\n");
      out.write("                    <li><a href=\"#\"><i class=\"fa fa-linkedin\"></i></a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-4\">\n");
      out.write("                <ul class=\"list-inline quicklinks pull-right\">\n");
      out.write("                    <li><a href=\"#\">Privacy Policy</a></li>\n");
      out.write("                    <li><a href=\"#\">Terms of Use</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<!-- jQuery -->\n");
      out.write("<script src=\"js/jquery.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Bootstrap Core JavaScript -->\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Plugin JavaScript -->\n");
      out.write("<script src=\"js/jquery.easing.min.js\"></script>\n");
      out.write("<script src=\"js/jquery.fittext.js\"></script>\n");
      out.write("<script src=\"js/wow.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Custom Theme JavaScript -->\n");
      out.write("<script src=\"js/clockwork.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
=======
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "_footer.jsp", out, false);
      out.write('\n');
>>>>>>> 9bd30ab842873ea5de372a0d5f99cced149ed30e
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
