var clockworkApp = angular.module('clockworkApp', []);

clockworkApp.controller('jobListCtrl', function ($scope) {
  $scope.jobs = [
  {'title': 'Bellhop needed @ Siloso Beach Resort, Sentosa.',
  'desc': 'Quisque mauris augue, molestie tincidunt condimentum isicing elit',
  'posted': 'Posted 2 days, 8 hours ago',
  'pay': '8/hr'},
  {'title': 'Bellhop needed @ Siloso Beach Resort, Sentosa.',
  'desc': 'Quisque mauris augue, molestie tincidunt condimentum isicing elit',
  'posted': 'Posted 2 days, 8 hours ago',
  'pay': '8/hr'},
  {'title': 'Bellhop needed @ Siloso Beach Resort, Sentosa.',
  'desc': 'Quisque mauris augue, molestie tincidunt condimentum isicing elit',
  'posted': 'Posted 2 days, 8 hours ago',
  'pay': '8/hr'},
  {'title': 'Bellhop needed @ Siloso Beach Resort, Sentosa.',
  'desc': 'Quisque mauris augue, molestie tincidunt condimentum isicing elit',
  'posted': 'Posted 2 days, 8 hours ago',
  'pay': '8/hr'},
  {'title': 'Bellhop needed @ Siloso Beach Resort, Sentosa.',
  'desc': 'Quisque mauris augue, molestie tincidunt condimentum isicing elit',
  'posted': 'Posted 2 days, 8 hours ago',
  'pay': '8/hr'},
  {'title': 'Bellhop needed @ Siloso Beach Resort, Sentosa.',
  'desc': 'Quisque mauris augue, molestie tincidunt condimentum isicing elit',
  'posted': 'Posted 2 days, 8 hours ago',
  'pay': '8/hr'},
  {'title': 'Bellhop needed @ Siloso Beach Resort, Sentosa.',
  'desc': 'Quisque mauris augue, molestie tincidunt condimentum isicing elit',
  'posted': 'Posted 2 days, 8 hours ago',
  'pay': '8/hr'},
  {'title': 'Bellhop needed @ Siloso Beach Resort, Sentosa.',
  'desc': 'Quisque mauris augue, molestie tincidunt condimentum isicing elit',
  'posted': 'Posted 2 days, 8 hours ago',
  'pay': '8/hr'},
  {'title': 'Bellhop needed @ Siloso Beach Resort, Sentosa.',
  'desc': 'Quisque mauris augue, molestie tincidunt condimentum isicing elit',
  'posted': 'Posted 2 days, 8 hours ago',
  'pay': '8/hr'},
  ];
});