/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-08-05 06:06:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.fc.demos;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class agenda_002dviews_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset='utf-8' />\r\n");
      out.write("<link href='../fullcalendar.css' rel='stylesheet' />\r\n");
      out.write("<link href='../fullcalendar.print.css' rel='stylesheet' media='print' />\r\n");
      out.write("<script src='../lib/moment.min.js'></script>\r\n");
      out.write("<script src='../lib/jquery.min.js'></script>\r\n");
      out.write("<script src='../fullcalendar.min.js'></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#calendar').fullCalendar({\r\n");
      out.write("\t\t\theader: {\r\n");
      out.write("\t\t\t\tleft: 'prev,next today',\r\n");
      out.write("\t\t\t\tcenter: 'title',\r\n");
      out.write("\t\t\t\tright: 'month,agendaWeek,agendaDay'\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdefaultDate: '2015-02-12',\r\n");
      out.write("\t\t\teditable: true,\r\n");
      out.write("\t\t\teventLimit: true, // allow \"more\" link when too many events\r\n");
      out.write("\t\t\tevents: [\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\ttitle: 'All Day Event',\r\n");
      out.write("\t\t\t\t\tstart: '2015-02-01'\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\ttitle: 'Long Event',\r\n");
      out.write("\t\t\t\t\tstart: '2015-02-07',\r\n");
      out.write("\t\t\t\t\tend: '2015-02-10'\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tid: 999,\r\n");
      out.write("\t\t\t\t\ttitle: 'Repeating Event',\r\n");
      out.write("\t\t\t\t\tstart: '2015-02-09T16:00:00'\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tid: 999,\r\n");
      out.write("\t\t\t\t\ttitle: 'Repeating Event',\r\n");
      out.write("\t\t\t\t\tstart: '2015-02-16T16:00:00'\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\ttitle: 'Conference',\r\n");
      out.write("\t\t\t\t\tstart: '2015-02-11',\r\n");
      out.write("\t\t\t\t\tend: '2015-02-13'\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\ttitle: 'Meeting',\r\n");
      out.write("\t\t\t\t\tstart: '2015-02-12T10:30:00',\r\n");
      out.write("\t\t\t\t\tend: '2015-02-12T12:30:00'\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\ttitle: 'Lunch',\r\n");
      out.write("\t\t\t\t\tstart: '2015-02-12T12:00:00'\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\ttitle: 'Meeting',\r\n");
      out.write("\t\t\t\t\tstart: '2015-02-12T14:30:00'\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\ttitle: 'Happy Hour',\r\n");
      out.write("\t\t\t\t\tstart: '2015-02-12T17:30:00'\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\ttitle: 'Dinner',\r\n");
      out.write("\t\t\t\t\tstart: '2015-02-12T20:00:00'\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\ttitle: 'Birthday Party',\r\n");
      out.write("\t\t\t\t\tstart: '2015-02-13T07:00:00'\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\ttitle: 'Click for Google',\r\n");
      out.write("\t\t\t\t\turl: 'http://google.com/',\r\n");
      out.write("\t\t\t\t\tstart: '2015-02-28'\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t]\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\tbody {\r\n");
      out.write("\t\tmargin: 40px 10px;\r\n");
      out.write("\t\tpadding: 0;\r\n");
      out.write("\t\tfont-family: \"Lucida Grande\",Helvetica,Arial,Verdana,sans-serif;\r\n");
      out.write("\t\tfont-size: 14px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#calendar {\r\n");
      out.write("\t\tmax-width: 900px;\r\n");
      out.write("\t\tmargin: 0 auto;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div id='calendar'></div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
